# Generated by Django 4.2.6 on 2023-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_ticket_flight_alter_ticket_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
